[package]
name = "pc_client"
version = "0.1.0"
authors = ["Andrew <klinks22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.16.7"
anyhow = "1"